######################################################################
##
## Filename: Prueba_1.udo
## Created on: Wed Nov 21 1:25:46 Hora estándar romance 2012
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
