######################################################################
##
## Filename: Bloque_tb.udo
## Created on: Sun Dec 09 17:00:26 Hora estándar romance 2012
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
