######################################################################
##
## Filename: bin2bcd.udo
## Created on: Tue Oct 23 13:47:19 Hora de verano romance 2012
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
